from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet


def generate_pdf(
    filename,
    prediction,
    confidence,
    details,
    symptom
):
    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>AI Medical Report</b>", styles["Title"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Patient Symptoms</b>", styles["Heading2"]))
    story.append(Paragraph(symptom, styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Predicted Disease</b>", styles["Heading2"]))
    story.append(Paragraph(prediction, styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Confidence</b>", styles["Heading2"]))
    story.append(Paragraph(f"{confidence}%", styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Description</b>", styles["Heading2"]))
    story.append(Paragraph(details["description"], styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Symptoms</b>", styles["Heading2"]))

    for item in details["symptoms"]:
        story.append(Paragraph("• " + item, styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Precautions</b>", styles["Heading2"]))

    for item in details["precautions"]:
        story.append(Paragraph("• " + item, styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Suggested Medicines</b>", styles["Heading2"]))

    for item in details["medicines"]:
        story.append(Paragraph("• " + item, styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Recommended Diet</b>", styles["Heading2"]))

    for item in details["diet"]:
        story.append(Paragraph("• " + item, styles["Normal"]))

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(Paragraph("<b>Doctor to Consult</b>", styles["Heading2"]))
    story.append(Paragraph(details["doctor"], styles["Normal"]))

    story.append(Paragraph("<br/><br/>", styles["Normal"]))

    story.append(
        Paragraph(
            "<b>Generated by AI Medical Assistant</b>",
            styles["Heading3"]
        )
    )

    doc.build(story)